FROM microsoft/mssql-server-windows-developer

LABEL com.coscale.monitoring='[{"PluginType":"MSSQL","Configuration":{"QUERY STATS":["true"],"INTEGRATED SECURITY":["LOGIN"],"USERNAME":["sa"],"PASSWORD":["$sa_password"],"HOSTNAME":["localhost"],"PORT":["1433"]}}]'
